monsieurbiz_search_search:
  path: /search/{query}
  methods: [GET]
  defaults:
    _controller: MonsieurBiz\SyliusSearchPlugin\Controller\SearchController:searchAction
  requirements:
    query: .+

monsieurbiz_search_post:
  path: /search
  methods: [POST]
  defaults:
    _controller: MonsieurBiz\SyliusSearchPlugin\Controller\SearchController:postAction
