sylius_ui:
  events:
    sylius.shop.layout.javascripts:
      blocks:
        monsieurbiz_search_javascripts:
          template: "@MonsieurBizSyliusSearchPlugin/_scripts.html.twig"
    sylius.shop.layout.header.content:
      blocks:
        search:
          template: "@MonsieurBizSyliusSearchPlugin/Header/form.html.twig"
          priority: 20
