framework:
  messenger:
    transports:
      async_search: '%env(MONSIEURBIZ_SEARCHPLUGIN_MESSENGER_TRANSPORT_DSN)%'

    routing:
      MonsieurBiz\SyliusSearchPlugin\Message\ProductReindexFromTaxon: async_search
      MonsieurBiz\SyliusSearchPlugin\Message\ProductReindexFromIds: async_search
