framework:
  messenger:
    transports:
      async_search:
        dsn: '%env(MONSIEURBIZ_SEARCHPLUGIN_MESSENGER_TRANSPORT_DSN)%'
        options:
          queue_name: 'monsieurbiz_search'

    routing:
      MonsieurBiz\SyliusSearchPlugin\Message\ProductReindexFromTaxon: async_search
      MonsieurBiz\SyliusSearchPlugin\Message\ProductReindexFromIds: async_search
