monsieurbiz_sylius_search:
  documents:
    monsieurbiz_product:
      source: 'Sylius\Component\Core\Model\ProductInterface'
      target: 'MonsieurBiz\SyliusSearchPlugin\Model\Product\ProductDTO'
      templates:
        item: '@MonsieurBizSyliusSearchPlugin/Search/product/_box.html.twig'
      #mapping_provider: '...' # by default monsieurbiz.search.mapper_provider
      #dataprovider: '...' # by default MonsieurBiz\SyliusSearchPlugin\Model\Datasource\RepositoryDatasource
  automapper_classes:
    product: '%sylius.model.product.class%'
    product_variant: '%sylius.model.product_variant.class%'
    product_attribute_value: '%sylius.model.product_attribute_value.class%'
