monsieurbiz_sylius_search:
  documents:
    product:
      source: 'Sylius\Component\Core\Model\ProductInterface'
      target: 'MonsieurBiz\SyliusSearchPlugin\Generated\Model\Product'
      #mapping_provider: '...' # by default monsieurbiz.search.mapper_provider
      #dataprovider: '...' # by default MonsieurBiz\SyliusSearchPlugin\Model\Datasource\RepositoryDatasource
