parameters:
  monsieurbiz.search.model.documentable.interface: MonsieurBiz\SyliusSearchPlugin\Model\Documentable\DocumentableInterface

services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $documentableRegistry: '@monsieurbiz.search.registry.documentable'
      $configurationDirectory: '@=service("file_locator").locate("@MonsieurBizSyliusSearchPlugin/Resources/config/elasticsearch")'

  _instanceof:
    MonsieurBiz\SyliusSearchPlugin\Model\Documentable\DocumentableInterface:
      tags: [ 'monsieurbiz.search.documentable' ]
      calls:
        - [setMappingProvider, ['@monsieurbiz.search.mapper_provider']]

  MonsieurBiz\SyliusSearchPlugin\:
    resource: '../../*'
    exclude: '../../{Entity,Migrations,Tests,Kernel.php}'

  JoliCode\Elastically\IndexNameMapper:
    arguments:
      $prefix: null # or a string to prefix index name
      $indexClassMapping: {}

  JoliCode\Elastically\Serializer\StaticContextBuilder:
    arguments:
      $mapping: {}

  JoliCode\Elastically\ResultSetBuilder:
    arguments:
      $indexNameMapper: '@JoliCode\Elastically\IndexNameMapper'
      $contextBuilder: '@JoliCode\Elastically\Serializer\StaticContextBuilder'
      $denormalizer: '@serializer'

  # ES Client configuration
  monsieurbiz.search.elasticsearch.client:
    class: JoliCode\Elastically\Client
    arguments:
      $config:
        host: '%env(ELASTICSEARCH_HOST)%'
      $logger: '@logger'
      $resultSetBuilder: '@JoliCode\Elastically\ResultSetBuilder'
      $indexNameMapper: '@JoliCode\Elastically\IndexNameMapper'

  JoliCode\Elastically\Mapping\YamlProvider: ~

  # Define the annotations provider arguments
  monsieurbiz.search.mapper_provider:
    class: MonsieurBiz\SyliusSearchPlugin\Mapping\YamlWithLocaleProvider
    decorates: JoliCode\Elastically\Mapping\YamlProvider
    arguments:
      $decorated: '@.inner'


  # Replace the mapping provider by our annotations provider
  JoliCode\Elastically\IndexBuilder:
    arguments:
      $client: '@monsieurbiz.search.elasticsearch.client'
      $mappingProvider: '@monsieurbiz.search.mapper_provider'

  monsieurbiz.search.registry.documentable:
    class: Sylius\Component\Registry\ServiceRegistry
    arguments:
      $className: '%monsieurbiz.search.model.documentable.interface%'
      $context: 'documentable'
