services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MonsieurBiz\SyliusSearchPlugin\:
    resource: '../../*'
    exclude: '../../{Entity,Migrations,Tests,Kernel.php}'
