monsieurbiz_sylius_settings:
  plugins:
    monsieurbiz.search:
      vendor_name: Monsieur Biz
      vendor_url:
      plugin_name: Search
      description: Search configuration
      icon: search
      use_locales: false
      classes:
        form: MonsieurBiz\SyliusSearchPlugin\Form\Type\Settings\SettingsSearchType
      default_values:
        instant_search_enabled__monsieurbiz_product: '%monsieurbiz.search.config.documents.monsieurbiz_product.instant_search_enabled%'
        limits__monsieurbiz_product: '%monsieurbiz.search.config.documents.monsieurbiz_product.limits%'
